import "./globals.css";
import React from "react";
import type { Metadata } from "next";
import MainHeader from "./components/MainHeader";
import Footer from "./components/Footer";

import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";

export const metadata: Metadata = {
  title: "Essence",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body>
          <MainHeader />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
          <Footer />
        </body>
      </SessionProvider>
    </html>
  );
}
